from typing import Dict
from app.ai.schemas.ai_schemas import PromptTemplateSchema

DEFAULT_PROMPT_TEMPLATES: Dict[str, PromptTemplateSchema] = {
    "linkedin_post": PromptTemplateSchema(
        id="linkedin_post",
        name="LinkedIn Thought Leadership Post",
        category="social_media",
        description="Creates high-engagement LinkedIn posts with professional structure and storytelling",
        system_prompt="You are an elite B2B LinkedIn creator writing for brand '{brand_name}'. Tone: {tone}. Target Audience: {target_audience}. Language: {language}.",
        user_prompt_template="Write a high-converting LinkedIn post about:\n\n{topic}\n\nAdditional Context:\n{context}\n\nRequirements:\n- Strong hook in first 2 lines\n- Clear spacing\n- Actionable takeaways\n- Strategic call to action: {call_to_action}",
        variables=["brand_name", "tone", "target_audience", "language", "topic", "context", "call_to_action"],
        version="1.1.0",
    ),
    "twitter_post": PromptTemplateSchema(
        id="twitter_post",
        name="X (Twitter) Standalone / Thread Starter",
        category="social_media",
        description="Crafts punchy, viral X (Twitter) posts under character constraints",
        system_prompt="You are a social media copywriter skilled in viral X/Twitter content. Tone: {tone}.",
        user_prompt_template="Create a viral X (Twitter) post or thread starter about: {topic}.\n\nContext: {context}.\nMake it concise, punchy, and include 1-2 relevant hashtags.",
        variables=["tone", "topic", "context"],
        version="1.1.0",
    ),
    "instagram_caption": PromptTemplateSchema(
        id="instagram_caption",
        name="Instagram Visual Story Caption",
        category="social_media",
        description="Generates engaging Instagram captions with emojis and structured hashtags",
        system_prompt="You are an Instagram content strategist for {brand_name}. Tone: {tone}.",
        user_prompt_template="Write a captivating Instagram caption for a post about: {topic}.\n\nContext: {context}.\nInclude engaging visual emojis, a prompt for comments, and 5-8 relevant hashtags.",
        variables=["brand_name", "tone", "topic", "context"],
        version="1.1.0",
    ),
    "facebook_post": PromptTemplateSchema(
        id="facebook_post",
        name="Facebook Community Post",
        category="social_media",
        description="Generates community-focused Facebook updates driving comments and shares",
        system_prompt="You are a Facebook community manager writing in a {tone} voice.",
        user_prompt_template="Create a friendly, community-driven Facebook post about: {topic}.\n\nContext: {context}.\nEncourage engagement and discussion in the comments.",
        variables=["tone", "topic", "context"],
        version="1.1.0",
    ),
    "blog_outline": PromptTemplateSchema(
        id="blog_outline",
        name="SEO Blog Article Outline",
        category="longform",
        description="Generates comprehensive, SEO-optimized blog article structures with headers",
        system_prompt="You are a senior content SEO strategist writing for {target_audience}.",
        user_prompt_template="Generate a detailed SEO blog article outline for topic: '{topic}'.\n\nContext/Keywords: {context}.\nInclude: Title ideas, H2 section headings, H3 sub-bullets, and key takeaways.",
        variables=["target_audience", "topic", "context"],
        version="1.1.0",
    ),
    "marketing_copy": PromptTemplateSchema(
        id="marketing_copy",
        name="High-Converting Product Marketing Copy",
        category="copywriting",
        description="Creates persuasive marketing copy using proven frameworks (PAS / AIDA)",
        system_prompt="You are a world-class direct response copywriter for {brand_name}. Tone: {tone}.",
        user_prompt_template="Write compelling marketing copy for product/offer: '{topic}'.\n\nDetails: {context}.\nUse Attention, Interest, Desire, and Action structure.",
        variables=["brand_name", "tone", "topic", "context"],
        version="1.1.0",
    ),
    "product_description": PromptTemplateSchema(
        id="product_description",
        name="E-Commerce & SaaS Product Description",
        category="copywriting",
        description="Highlights feature benefits and unique value propositions for product listings",
        system_prompt="You are an e-commerce conversion specialist.",
        user_prompt_template="Write a crisp, benefit-focused product description for: {topic}.\n\nFeature details: {context}.\nHighlight top benefits and target use cases.",
        variables=["topic", "context"],
        version="1.1.0",
    ),
    "call_to_action": PromptTemplateSchema(
        id="call_to_action",
        name="High-Conversion Call To Action (CTA)",
        category="copywriting",
        description="Generates magnetic CTA variations for landing pages, emails, or social copy",
        system_prompt="You are a conversion rate optimization specialist.",
        user_prompt_template="Generate 5 compelling call-to-action phrases for goal: {topic}.\n\nTarget audience: {target_audience}. Context: {context}.",
        variables=["topic", "target_audience", "context"],
        version="1.1.0",
    ),
    "hashtag_generation": PromptTemplateSchema(
        id="hashtag_generation",
        name="Niche & Viral Hashtags Generator",
        category="social_media",
        description="Generates categorized high-reach and niche-specific social hashtags",
        system_prompt="You are a social search optimization assistant.",
        user_prompt_template="Generate 20 relevant hashtags for topic: '{topic}'. Categorize into high-volume, medium-niche, and hyper-targeted.",
        variables=["topic"],
        version="1.1.0",
    ),
    "rewrite_content": PromptTemplateSchema(
        id="rewrite_content",
        name="Content Polisher & Tone Rewriter",
        category="content_editing",
        description="Rewrites draft content into target brand tone while boosting clarity",
        system_prompt="You are an expert editor. Desired tone: {tone}. Target Language: {language}.",
        user_prompt_template="Rewrite and polish the following content:\n\n{context}\n\nSpecific instructions: {topic}",
        variables=["tone", "language", "context", "topic"],
        version="1.1.0",
    ),
    "expand_content": PromptTemplateSchema(
        id="expand_content",
        name="Content Expander & Elaborator",
        category="content_editing",
        description="Fleshes out brief outlines or short notes into rich, detailed prose",
        system_prompt="You are a content writer skilled in deep explanation and storytelling.",
        user_prompt_template="Expand the following bullet points/text into a full detailed draft:\n\n{context}\n\nAdditional guidance: {topic}",
        variables=["context", "topic"],
        version="1.1.0",
    ),
    "shorten_content": PromptTemplateSchema(
        id="shorten_content",
        name="Content Condenser & Shortener",
        category="content_editing",
        description="Condenses lengthy copy into clear, impactful bullet points or summaries",
        system_prompt="You are a concise executive editor.",
        user_prompt_template="Shorten and condense the following text while keeping core insights intact:\n\n{context}",
        variables=["context"],
        version="1.1.0",
    ),
    "summarize_content": PromptTemplateSchema(
        id="summarize_content",
        name="Key Takeaways & Executive Summary",
        category="content_editing",
        description="Extracts key takeaways and executive summary points from source text",
        system_prompt="You are a research analyst.",
        user_prompt_template="Extract top 5 executive takeaways and a 2-sentence summary from:\n\n{context}",
        variables=["context"],
        version="1.1.0",
    ),
}
