// Mock data for the entire SocialPilot AI application

export const kpiData = [
  {
    id: "posts_published",
    label: "Posts Published",
    value: 2847,
    change: +12.4,
    suffix: "",
    color: "blue",
    icon: "send",
  },
  {
    id: "scheduled_posts",
    label: "Scheduled Posts",
    value: 143,
    change: +8.1,
    suffix: "",
    color: "violet",
    icon: "calendar",
  },
  {
    id: "active_agents",
    label: "Active Agents",
    value: 19,
    change: +2,
    suffix: "",
    color: "emerald",
    icon: "bot",
  },
  {
    id: "automation_health",
    label: "Automation Health",
    value: 98.7,
    change: +0.3,
    suffix: "%",
    color: "gold",
    icon: "activity",
  },
  {
    id: "accounts_connected",
    label: "Accounts Connected",
    value: 34,
    change: +4,
    suffix: "",
    color: "sky",
    icon: "link",
  },
  {
    id: "ai_credits",
    label: "AI Credits",
    value: 48200,
    change: -3200,
    suffix: "",
    color: "violet",
    icon: "zap",
  },
  {
    id: "reach",
    label: "Total Reach",
    value: 1_240_000,
    change: +18.6,
    suffix: "",
    color: "blue",
    icon: "globe",
  },
  {
    id: "engagement",
    label: "Avg Engagement",
    value: 6.4,
    change: +1.2,
    suffix: "%",
    color: "emerald",
    icon: "heart",
  },
];

export const engagementData = [
  { date: "Jan", linkedin: 4200, instagram: 6800, twitter: 3100, facebook: 2400 },
  { date: "Feb", linkedin: 5100, instagram: 7200, twitter: 3800, facebook: 2900 },
  { date: "Mar", linkedin: 4800, instagram: 8100, twitter: 4200, facebook: 3100 },
  { date: "Apr", linkedin: 6200, instagram: 9400, twitter: 5100, facebook: 3800 },
  { date: "May", linkedin: 7100, instagram: 10200, twitter: 5800, facebook: 4200 },
  { date: "Jun", linkedin: 8400, instagram: 12100, twitter: 6800, facebook: 5100 },
  { date: "Jul", linkedin: 9200, instagram: 13400, twitter: 7200, facebook: 5800 },
];

export const followerGrowthData = [
  { date: "Week 1", followers: 12400 },
  { date: "Week 2", followers: 13100 },
  { date: "Week 3", followers: 14200 },
  { date: "Week 4", followers: 15800 },
  { date: "Week 5", followers: 17200 },
  { date: "Week 6", followers: 19400 },
  { date: "Week 7", followers: 21800 },
  { date: "Week 8", followers: 24100 },
];

export const contentScoreData = [
  { subject: "Engagement", value: 88 },
  { subject: "Reach", value: 76 },
  { subject: "Consistency", value: 92 },
  { subject: "Brand Voice", value: 85 },
  { subject: "SEO", value: 79 },
  { subject: "Visuals", value: 91 },
];

export const agents = [
  {
    id: "master_orchestrator",
    name: "Master Orchestrator",
    role: "Coordinates all agents and manages workflow execution",
    status: "active",
    health: 99.2,
    successRate: 98.8,
    tasksCompleted: 14820,
    lastRun: "2 min ago",
    memory: "1.2 GB",
    execTime: "340ms avg",
    currentTask: "Orchestrating Campaign #47 content pipeline",
    color: "blue",
    icon: "brain",
  },
  {
    id: "trend_agent",
    name: "Trend Agent",
    role: "Detects viral trends across platforms in real-time",
    status: "active",
    health: 97.4,
    successRate: 96.1,
    tasksCompleted: 8420,
    lastRun: "5 min ago",
    memory: "480 MB",
    execTime: "180ms avg",
    currentTask: "Scanning TikTok, Twitter, Reddit for trending topics",
    color: "violet",
    icon: "trending-up",
  },
  {
    id: "research_agent",
    name: "Research Agent",
    role: "Deep research on topics, industries and competitors",
    status: "active",
    health: 98.1,
    successRate: 97.4,
    tasksCompleted: 6210,
    lastRun: "12 min ago",
    memory: "620 MB",
    execTime: "2.4s avg",
    currentTask: "Researching AI industry news for LinkedIn campaign",
    color: "emerald",
    icon: "search",
  },
  {
    id: "writer_agent",
    name: "Writer Agent",
    role: "Generates platform-optimized content for all channels",
    status: "active",
    health: 99.6,
    successRate: 99.1,
    tasksCompleted: 22140,
    lastRun: "1 min ago",
    memory: "340 MB",
    execTime: "1.8s avg",
    currentTask: "Drafting 5 LinkedIn posts for SaaS campaign",
    color: "gold",
    icon: "pen-tool",
  },
  {
    id: "editor_agent",
    name: "Editor Agent",
    role: "Reviews, refines and improves all generated content",
    status: "active",
    health: 98.9,
    successRate: 98.3,
    tasksCompleted: 19820,
    lastRun: "3 min ago",
    memory: "280 MB",
    execTime: "1.2s avg",
    currentTask: "Editing and optimizing post #342",
    color: "sky",
    icon: "edit-3",
  },
  {
    id: "brand_voice_agent",
    name: "Brand Voice Agent",
    role: "Ensures all content aligns with brand guidelines",
    status: "active",
    health: 99.8,
    successRate: 99.4,
    tasksCompleted: 18200,
    lastRun: "2 min ago",
    memory: "190 MB",
    execTime: "640ms avg",
    currentTask: "Checking brand voice consistency on 3 posts",
    color: "violet",
    icon: "shield-check",
  },
  {
    id: "seo_agent",
    name: "SEO Agent",
    role: "Optimizes content for search engines and discoverability",
    status: "active",
    health: 97.8,
    successRate: 96.9,
    tasksCompleted: 12840,
    lastRun: "8 min ago",
    memory: "220 MB",
    execTime: "890ms avg",
    currentTask: "Optimizing keywords for blog campaign",
    color: "emerald",
    icon: "bar-chart-2",
  },
  {
    id: "hashtag_agent",
    name: "Hashtag Agent",
    role: "Generates optimal hashtag sets for maximum reach",
    status: "active",
    health: 98.4,
    successRate: 97.8,
    tasksCompleted: 16400,
    lastRun: "4 min ago",
    memory: "140 MB",
    execTime: "420ms avg",
    currentTask: "Generating hashtags for Instagram batch",
    color: "blue",
    icon: "hash",
  },
  {
    id: "image_agent",
    name: "Image Agent",
    role: "Creates AI-generated visuals for all content types",
    status: "active",
    health: 96.2,
    successRate: 94.8,
    tasksCompleted: 8920,
    lastRun: "15 min ago",
    memory: "1.8 GB",
    execTime: "12.4s avg",
    currentTask: "Generating 8 carousel images for product launch",
    color: "gold",
    icon: "image",
  },
  {
    id: "scheduler_agent",
    name: "Scheduler Agent",
    role: "Finds optimal posting times using ML predictions",
    status: "active",
    health: 99.1,
    successRate: 98.7,
    tasksCompleted: 24100,
    lastRun: "1 min ago",
    memory: "180 MB",
    execTime: "210ms avg",
    currentTask: "Scheduling 12 posts across 6 accounts",
    color: "sky",
    icon: "clock",
  },
  {
    id: "publisher_agent",
    name: "Publisher Agent",
    role: "Publishes content across all connected platforms",
    status: "active",
    health: 99.7,
    successRate: 99.5,
    tasksCompleted: 28400,
    lastRun: "8 min ago",
    memory: "160 MB",
    execTime: "1.1s avg",
    currentTask: "Publishing scheduled posts for morning batch",
    color: "emerald",
    icon: "send",
  },
  {
    id: "analytics_agent",
    name: "Analytics Agent",
    role: "Tracks and analyzes performance metrics continuously",
    status: "active",
    health: 98.3,
    successRate: 97.9,
    tasksCompleted: 42800,
    lastRun: "30 sec ago",
    memory: "440 MB",
    execTime: "340ms avg",
    currentTask: "Processing analytics for 34 accounts",
    color: "violet",
    icon: "pie-chart",
  },
  {
    id: "learning_agent",
    name: "Learning Agent",
    role: "Continuously improves performance from analytics data",
    status: "active",
    health: 97.1,
    successRate: 96.4,
    tasksCompleted: 3820,
    lastRun: "2 hours ago",
    memory: "920 MB",
    execTime: "45s avg",
    currentTask: "Training on last 7 days of engagement data",
    color: "gold",
    icon: "refresh-cw",
  },
  {
    id: "competitor_agent",
    name: "Competitor Agent",
    role: "Monitors and analyzes competitor content strategies",
    status: "active",
    health: 96.8,
    successRate: 95.2,
    tasksCompleted: 5640,
    lastRun: "1 hour ago",
    memory: "380 MB",
    execTime: "8.2s avg",
    currentTask: "Analyzing 12 competitor accounts this week",
    color: "blue",
    icon: "eye",
  },
  {
    id: "news_agent",
    name: "News Agent",
    role: "Aggregates and curates relevant industry news",
    status: "active",
    health: 98.6,
    successRate: 97.3,
    tasksCompleted: 9240,
    lastRun: "20 min ago",
    memory: "240 MB",
    execTime: "3.4s avg",
    currentTask: "Fetching tech news from 48 RSS sources",
    color: "sky",
    icon: "newspaper",
  },
  {
    id: "fact_checker",
    name: "Fact Checker",
    role: "Verifies facts and prevents misinformation",
    status: "active",
    health: 99.3,
    successRate: 98.9,
    tasksCompleted: 11800,
    lastRun: "6 min ago",
    memory: "310 MB",
    execTime: "2.1s avg",
    currentTask: "Verifying statistics in 4 pending posts",
    color: "emerald",
    icon: "check-circle",
  },
  {
    id: "compliance_agent",
    name: "Compliance Agent",
    role: "Ensures content meets platform and legal requirements",
    status: "active",
    health: 99.9,
    successRate: 99.8,
    tasksCompleted: 16200,
    lastRun: "5 min ago",
    memory: "200 MB",
    execTime: "780ms avg",
    currentTask: "Compliance check on 8 posts in approval queue",
    color: "violet",
    icon: "shield",
  },
  {
    id: "qa_agent",
    name: "Quality Assurance Agent",
    role: "Final quality check before publishing",
    status: "active",
    health: 99.6,
    successRate: 99.2,
    tasksCompleted: 21400,
    lastRun: "3 min ago",
    memory: "175 MB",
    execTime: "1.4s avg",
    currentTask: "QA review for batch publish at 9:00 AM",
    color: "gold",
    icon: "star",
  },
  {
    id: "video_agent",
    name: "Video Agent",
    role: "Creates AI-generated short-form video content",
    status: "idle",
    health: 94.1,
    successRate: 92.4,
    tasksCompleted: 1820,
    lastRun: "3 hours ago",
    memory: "2.4 GB",
    execTime: "2.8min avg",
    currentTask: "Idle — awaiting video generation requests",
    color: "sky",
    icon: "video",
  },
];

export const platforms = [
  { id: "linkedin", name: "LinkedIn", color: "#0077B5", connected: true, accounts: 3 },
  { id: "instagram", name: "Instagram", color: "#E1306C", connected: true, accounts: 5 },
  { id: "facebook", name: "Facebook", color: "#1877F2", connected: true, accounts: 4 },
  { id: "twitter", name: "Twitter/X", color: "#000000", connected: true, accounts: 6 },
  { id: "threads", name: "Threads", color: "#101010", connected: true, accounts: 2 },
  { id: "pinterest", name: "Pinterest", color: "#BD081C", connected: false, accounts: 0 },
  { id: "youtube", name: "YouTube", color: "#FF0000", connected: true, accounts: 2 },
  { id: "tiktok", name: "TikTok", color: "#010101", connected: false, accounts: 0 },
  { id: "reddit", name: "Reddit", color: "#FF4500", connected: false, accounts: 0 },
];

export const recentActivity = [
  {
    id: 1,
    agent: "Publisher Agent",
    action: "Published LinkedIn post",
    target: "5 Tips for B2B Lead Generation in 2025",
    time: "2 min ago",
    status: "success",
    platform: "linkedin",
  },
  {
    id: 2,
    agent: "Trend Agent",
    action: "Detected trending topic",
    target: "#AIProductivity trending +840%",
    time: "5 min ago",
    status: "info",
    platform: "twitter",
  },
  {
    id: 3,
    agent: "Writer Agent",
    action: "Generated 3 posts",
    target: "Instagram campaign — Product Launch Series",
    time: "8 min ago",
    status: "success",
    platform: "instagram",
  },
  {
    id: 4,
    agent: "Image Agent",
    action: "Generated carousel",
    target: "8-slide product comparison carousel",
    time: "15 min ago",
    status: "success",
    platform: "instagram",
  },
  {
    id: 5,
    agent: "Compliance Agent",
    action: "Flagged content",
    target: "Post #284 — requires CTA adjustment",
    time: "22 min ago",
    status: "warning",
    platform: "facebook",
  },
  {
    id: 6,
    agent: "Analytics Agent",
    action: "Insight generated",
    target: "Best posting time: Tuesday 10-11 AM",
    time: "45 min ago",
    status: "info",
    platform: "linkedin",
  },
];

export const scheduledPosts = [
  {
    id: 1,
    title: "AI Revolution in B2B Marketing",
    platform: "linkedin",
    scheduledAt: "Today, 09:00 AM",
    status: "scheduled",
    thumbnail: null,
  },
  {
    id: 2,
    title: "5 Instagram Growth Hacks for 2025",
    platform: "instagram",
    scheduledAt: "Today, 11:30 AM",
    status: "scheduled",
    thumbnail: null,
  },
  {
    id: 3,
    title: "Weekly Industry News Roundup",
    platform: "twitter",
    scheduledAt: "Today, 02:00 PM",
    status: "scheduled",
    thumbnail: null,
  },
  {
    id: 4,
    title: "Product Launch Announcement",
    platform: "facebook",
    scheduledAt: "Tomorrow, 10:00 AM",
    status: "pending_approval",
    thumbnail: null,
  },
  {
    id: 5,
    title: "Customer Success Story — TechCorp",
    platform: "linkedin",
    scheduledAt: "Tomorrow, 02:30 PM",
    status: "draft",
    thumbnail: null,
  },
];

export const integrations = [
  // Social Media
  { id: "linkedin", name: "LinkedIn", category: "Social Media", connected: true, logo: "🔗" },
  { id: "instagram", name: "Instagram", category: "Social Media", connected: true, logo: "📸" },
  { id: "facebook", name: "Facebook", category: "Social Media", connected: true, logo: "👍" },
  { id: "twitter", name: "Twitter/X", category: "Social Media", connected: true, logo: "𝕏" },
  { id: "threads", name: "Threads", category: "Social Media", connected: true, logo: "🧵" },
  { id: "pinterest", name: "Pinterest", category: "Social Media", connected: false, logo: "📌" },
  { id: "youtube", name: "YouTube", category: "Social Media", connected: true, logo: "▶️" },
  { id: "tiktok", name: "TikTok", category: "Social Media", connected: false, logo: "🎵" },
  { id: "reddit", name: "Reddit", category: "Social Media", connected: false, logo: "🤖" },
  // AI Providers
  { id: "openai", name: "OpenAI", category: "AI Providers", connected: true, logo: "⚡" },
  { id: "anthropic", name: "Anthropic", category: "AI Providers", connected: true, logo: "🧠" },
  { id: "gemini", name: "Google Gemini", category: "AI Providers", connected: false, logo: "✨" },
  { id: "openrouter", name: "OpenRouter", category: "AI Providers", connected: false, logo: "🔀" },
  { id: "replicate", name: "Replicate", category: "AI Providers", connected: true, logo: "🔄" },
  { id: "stability", name: "Stability AI", category: "AI Providers", connected: false, logo: "🎨" },
  // Cloud & Storage
  { id: "gdrive", name: "Google Drive", category: "Cloud Storage", connected: true, logo: "📁" },
  { id: "dropbox", name: "Dropbox", category: "Cloud Storage", connected: false, logo: "📦" },
  { id: "onedrive", name: "OneDrive", category: "Cloud Storage", connected: false, logo: "☁️" },
  { id: "cloudinary", name: "Cloudinary", category: "Cloud Storage", connected: true, logo: "🖼️" },
  { id: "aws", name: "AWS S3", category: "Cloud Storage", connected: true, logo: "🌐" },
  // Communication
  { id: "slack", name: "Slack", category: "Communication", connected: true, logo: "💬" },
  { id: "discord", name: "Discord", category: "Communication", connected: false, logo: "🎮" },
  // Publishing
  { id: "wordpress", name: "WordPress", category: "Publishing", connected: false, logo: "📝" },
  { id: "medium", name: "Medium", category: "Publishing", connected: false, logo: "M" },
];

export const clients = [
  { id: 1, name: "TechCorp Inc.", logo: "TC", plan: "Enterprise", accounts: 12, posts: 1842, status: "active" },
  { id: 2, name: "GreenBrand", logo: "GB", plan: "Pro", accounts: 6, posts: 924, status: "active" },
  { id: 3, name: "Luxe Fashion", logo: "LF", plan: "Pro", accounts: 8, posts: 1240, status: "active" },
  { id: 4, name: "StartupX", logo: "SX", plan: "Starter", accounts: 3, posts: 412, status: "active" },
  { id: 5, name: "MediaHouse", logo: "MH", plan: "Enterprise", accounts: 18, posts: 3420, status: "active" },
];

export const teamMembers = [
  { id: 1, name: "Alex Rivera", role: "Admin", email: "alex@company.com", status: "active", avatar: "AR" },
  { id: 2, name: "Sarah Chen", role: "Content Manager", email: "sarah@company.com", status: "active", avatar: "SC" },
  { id: 3, name: "Marcus Johnson", role: "Analyst", email: "marcus@company.com", status: "active", avatar: "MJ" },
  { id: 4, name: "Priya Sharma", role: "Designer", email: "priya@company.com", status: "active", avatar: "PS" },
  { id: 5, name: "Tom Wilson", role: "Viewer", email: "tom@company.com", status: "pending", avatar: "TW" },
];

export const heatmapData = Array.from({ length: 7 }, (_, day) =>
  Array.from({ length: 24 }, (_, hour) => ({
    day,
    hour,
    value: Math.floor(
      Math.random() * 100 *
      (hour >= 8 && hour <= 21 ? 1 : 0.15) *
      (day < 5 ? 1 : 0.6)
    ),
  }))
).flat();
