"use client";

import { create } from "zustand";
import { persist } from "zustand/middleware";
import { kpiData, agents as defaultAgents, scheduledPosts as defaultPosts, integrations as defaultIntegrations } from "@/lib/mock-data";

export interface PostItem {
  id: string;
  title: string;
  content: string;
  platform: "linkedin" | "instagram" | "twitter" | "facebook" | "threads" | "blog";
  scheduledAt: string;
  status: "scheduled" | "pending_approval" | "published" | "draft" | "rejected";
  imageUrl?: string;
  createdAt: string;
  qualityScore?: number;
}

export interface AgentItem {
  id: string;
  name: string;
  role: string;
  status: "active" | "idle" | "running" | "error";
  health: number;
  successRate: number;
  tasksCompleted: number;
  lastRun: string;
  memory: string;
  execTime: string;
  currentTask: string;
  color: string;
  icon: string;
}

export interface GeneratedImageItem {
  id: string;
  prompt: string;
  style: string;
  aspectRatio: string;
  url: string;
  createdAt: string;
}

export interface AppSettings {
  openaiKey: string;
  anthropicKey: string;
  geminiKey: string;
  replicateKey: string;
  autoPublish: boolean;
  brandName: string;
  brandTone: string;
}

interface AppStoreState {
  // Posts
  posts: PostItem[];
  addPost: (post: Omit<PostItem, "id" | "createdAt">) => void;
  updatePostStatus: (id: string, status: PostItem["status"]) => void;
  deletePost: (id: string) => void;

  // Agents
  agents: AgentItem[];
  toggleAgent: (id: string) => void;
  updateAgentTask: (id: string, task: string, status?: AgentItem["status"]) => void;

  // Image History
  images: GeneratedImageItem[];
  addImage: (img: Omit<GeneratedImageItem, "id" | "createdAt">) => void;

  // Settings & Keys
  settings: AppSettings;
  updateSettings: (newSettings: Partial<AppSettings>) => void;
}

const initialPosts: PostItem[] = defaultPosts.map((p) => ({
  id: String(p.id),
  title: p.title,
  content: p.title + "\n\nGenerated by SocialPilot AI Agentic System. #AI #Automation #Growth",
  platform: p.platform as any,
  scheduledAt: p.scheduledAt,
  status: p.status as any,
  createdAt: new Date().toISOString(),
  qualityScore: 92,
}));

const initialAgents: AgentItem[] = defaultAgents.map((a) => ({
  ...a,
  status: a.status as any,
}));

export const useAppStore = create<AppStoreState>()(
  persist(
    (set, get) => ({
      posts: initialPosts,
      addPost: (postData) => {
        const newPost: PostItem = {
          ...postData,
          id: "post-" + Date.now() + "-" + Math.random().toString(36).substring(2, 7),
          createdAt: new Date().toISOString(),
        };
        set((state) => ({ posts: [newPost, ...state.posts] }));
      },
      updatePostStatus: (id, status) => {
        set((state) => ({
          posts: state.posts.map((p) => (p.id === id ? { ...p, status } : p)),
        }));
      },
      deletePost: (id) => {
        set((state) => ({
          posts: state.posts.filter((p) => p.id !== id),
        }));
      },

      agents: initialAgents,
      toggleAgent: (id) => {
        set((state) => ({
          agents: state.agents.map((a) =>
            a.id === id
              ? {
                  ...a,
                  status: a.status === "active" ? "idle" : "active",
                }
              : a
          ),
        }));
      },
      updateAgentTask: (id, task, status) => {
        set((state) => ({
          agents: state.agents.map((a) =>
            a.id === id
              ? {
                  ...a,
                  currentTask: task,
                  status: status || a.status,
                  tasksCompleted: a.tasksCompleted + 1,
                  lastRun: "Just now",
                }
              : a
          ),
        }));
      },

      images: [
        {
          id: "img-1",
          prompt: "Professional AI tech workspace with blue holograms and ultra-clean aesthetic",
          style: "photorealistic",
          aspectRatio: "1:1",
          url: "https://image.pollinations.ai/prompt/Professional%20AI%20tech%20workspace%20with%20blue%20holograms?width=800&height=800&nologo=true",
          createdAt: new Date().toISOString(),
        },
      ],
      addImage: (imgData) => {
        const newImg: GeneratedImageItem = {
          ...imgData,
          id: "img-" + Date.now(),
          createdAt: new Date().toISOString(),
        };
        set((state) => ({ images: [newImg, ...state.images] }));
      },

      settings: {
        openaiKey: "",
        anthropicKey: "",
        geminiKey: "",
        replicateKey: "",
        autoPublish: true,
        brandName: "SocialPilot AI",
        brandTone: "Professional & Authoritative",
      },
      updateSettings: (newSettings) => {
        set((state) => ({
          settings: { ...state.settings, ...newSettings },
        }));
      },
    }),
    {
      name: "socialpilot-app-storage",
    }
  )
);
