"use client";

import { create } from "zustand";
import { persist } from "zustand/middleware";
import { agents as defaultAgents, scheduledPosts as defaultPosts } from "@/lib/mock-data";

export interface PostItem {
  id: string;
  title: string;
  content: string;
  platform: "linkedin" | "instagram" | "twitter" | "facebook" | "threads" | "blog";
  scheduledAt: string;
  status: "scheduled" | "pending_approval" | "published" | "draft" | "rejected" | "failed";
  imageUrl?: string;
  createdAt: string;
  qualityScore?: number;
  author?: {
    name: string;
    avatar: string;
    role: string;
  };
  failureReason?: string;
  failureLogSnippet?: string;
  retryCount?: number;
  campaignId?: string;
}

export interface AgentItem {
  id: string;
  name: string;
  role: string;
  status: "active" | "idle" | "running" | "error";
  health: number;
  successRate: number;
  tasksCompleted: number;
  lastRun: string;
  memory: string;
  execTime: string;
  currentTask: string;
  color: string;
  icon: string;
}

export interface GeneratedImageItem {
  id: string;
  prompt: string;
  style: string;
  aspectRatio: string;
  url: string;
  createdAt: string;
}

export interface AppSettings {
  openaiKey: string;
  anthropicKey: string;
  geminiKey: string;
  replicateKey: string;
  autoPublish: boolean;
  brandName: string;
  brandTone: string;
}

interface AppStoreState {
  // Posts & Queue
  posts: PostItem[];
  addPost: (post: Omit<PostItem, "id" | "createdAt">) => void;
  updatePostStatus: (id: string, status: PostItem["status"]) => void;
  approveAllPending: () => void;
  retryFailedPost: (id: string) => void;
  deletePost: (id: string) => void;
  publishScheduledPosts: () => void;

  // Agents Fleet
  agents: AgentItem[];
  toggleAgent: (id: string) => void;
  updateAgentTask: (id: string, task: string, status?: AgentItem["status"]) => void;
  triggerAgentTask: (agentId: string, taskName: string) => void;

  // Image History
  images: GeneratedImageItem[];
  addImage: (img: Omit<GeneratedImageItem, "id" | "createdAt">) => void;

  // Settings & Keys
  settings: AppSettings;
  updateSettings: (newSettings: Partial<AppSettings>) => void;
}

const initialPosts: PostItem[] = defaultPosts.map((p) => ({
  id: String(p.id),
  title: p.title,
  content: p.title + "\n\nGenerated by SocialPilot AI Agentic Engine. #AI #Automation #Growth",
  platform: p.platform as any,
  scheduledAt: p.scheduledAt,
  status: p.status as any,
  createdAt: new Date().toISOString(),
  qualityScore: 92,
  author: { name: "AI Agent", avatar: "AI", role: "Autonomous Agent" },
  retryCount: 0,
}));

const initialAgents: AgentItem[] = defaultAgents.map((a) => ({
  ...a,
  status: a.status as any,
}));

export const useAppStore = create<AppStoreState>()(
  persist(
    (set, get) => ({
      posts: initialPosts,
      addPost: (postData) => {
        const newPost: PostItem = {
          ...postData,
          id: "post-" + Date.now() + "-" + Math.random().toString(36).substring(2, 7),
          createdAt: new Date().toISOString(),
          retryCount: postData.retryCount || 0,
          author: postData.author || { name: "Sarah Jenkins", avatar: "SJ", role: "Content Strategist" },
        };
        set((state) => ({ posts: [newPost, ...state.posts] }));
      },
      updatePostStatus: (id, status) => {
        set((state) => ({
          posts: state.posts.map((p) => (p.id === id ? { ...p, status } : p)),
        }));
      },
      approveAllPending: () => {
        set((state) => ({
          posts: state.posts.map((p) => (p.status === "pending_approval" ? { ...p, status: "scheduled" } : p)),
        }));
      },
      retryFailedPost: (id) => {
        set((state) => ({
          posts: state.posts.map((p) =>
            p.id === id
              ? {
                  ...p,
                  status: "scheduled",
                  retryCount: (p.retryCount || 0) + 1,
                  failureReason: undefined,
                  failureLogSnippet: undefined,
                }
              : p
          ),
        }));
      },
      deletePost: (id) => {
        set((state) => ({
          posts: state.posts.filter((p) => p.id !== id),
        }));
      },
      publishScheduledPosts: () => {
        // Auto-sync action: convert scheduled posts into published state periodically
        set((state) => ({
          posts: state.posts.map((p) => {
            if (p.status === "scheduled" && Math.random() > 0.8) {
              return { ...p, status: "published" };
            }
            return p;
          }),
        }));
      },

      agents: initialAgents,
      toggleAgent: (id) => {
        set((state) => ({
          agents: state.agents.map((a) =>
            a.id === id
              ? {
                  ...a,
                  status: a.status === "active" ? "idle" : "active",
                }
              : a
          ),
        }));
      },
      updateAgentTask: (id, task, status) => {
        set((state) => ({
          agents: state.agents.map((a) =>
            a.id === id
              ? {
                  ...a,
                  currentTask: task,
                  status: status || a.status,
                  tasksCompleted: a.tasksCompleted + 1,
                  lastRun: "Just now",
                }
              : a
          ),
        }));
      },
      triggerAgentTask: (agentId, taskName) => {
        const state = get();
        const targetAgent = state.agents.find((a) => a.id === agentId);
        if (!targetAgent) return;

        // Update agent stats
        state.updateAgentTask(agentId, taskName, "running");

        // Automatically generate a new post draft from this agent
        const platforms: PostItem["platform"][] = ["linkedin", "twitter", "instagram", "facebook"];
        const chosenPlatform = platforms[Math.floor(Math.random() * platforms.length)];

        setTimeout(() => {
          get().addPost({
            title: `🤖 ${targetAgent.name}: ${taskName}`,
            content: `Autonomous execution result from ${targetAgent.name}. Strategy optimization & content distribution verified. #AI #Automation`,
            platform: chosenPlatform,
            scheduledAt: "Tomorrow, 10:00 AM",
            status: "pending_approval",
            qualityScore: Math.floor(Math.random() * 10) + 90,
            author: { name: targetAgent.name, avatar: "AI", role: targetAgent.role },
          });

          get().updateAgentTask(agentId, "Idle / Standing by", "active");
        }, 1200);
      },

      images: [
        {
          id: "img-1",
          prompt: "Professional AI tech workspace with blue holograms and ultra-clean aesthetic",
          style: "photorealistic",
          aspectRatio: "1:1",
          url: "https://image.pollinations.ai/prompt/Professional%20AI%20tech%20workspace%20with%20blue%20holograms?width=800&height=800&nologo=true",
          createdAt: new Date().toISOString(),
        },
      ],
      addImage: (imgData) => {
        const newImg: GeneratedImageItem = {
          ...imgData,
          id: "img-" + Date.now(),
          createdAt: new Date().toISOString(),
        };
        set((state) => ({ images: [newImg, ...state.images] }));
      },

      settings: {
        openaiKey: "",
        anthropicKey: "",
        geminiKey: "",
        replicateKey: "",
        autoPublish: true,
        brandName: "SocialPilot AI",
        brandTone: "Professional & Authoritative",
      },
      updateSettings: (newSettings) => {
        set((state) => ({
          settings: { ...state.settings, ...newSettings },
        }));
      },
    }),
    {
      name: "socialpilot-app-storage",
    }
  )
);
